name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Dependencies
        run: uv sync

      - name: Run Tests
        run: uv run pytest

      - name: Run Flake8
        run: uv run flake8 sample_app

      - name: Simulated Deployment
        run: echo "Deployment Successful!"
